@echo off
rem This file is automatically generated.

if "%1" == "run" goto run
if "%1" == "long" goto long
goto run

:run
@echo on
@echo '(no change)'
ruby .\monty.rb 100 | ruby ..\count.rb
@echo '(change)'
ruby .\monty.rb -c 100 | ruby ..\count.rb
@echo off
goto end

:long
@echo on
@echo '(no change)'
ruby .\monty.rb 10000 | ruby ..\count.rb
@echo '(change)'
ruby .\monty.rb -c 10000 | ruby ..\count.rb
@echo off
goto end

:end
