run:
	@echo '(no change)'
	./monty.rb 100 | ../count.rb
	@echo '(change)'
	./monty.rb -c 100 | ../count.rb

long:
	@echo '(no change)'
	./monty.rb 10000 | ../count.rb
	@echo '(change)'
	./monty.rb -c 10000 | ../count.rb
