@echo off
rem This file is automatically generated.

if "%1" == "run" goto run
if "%1" == "long" goto long
goto run

:run
@echo on
ruby .\toss.rb -p=0.1 1000 | ruby ..\monitor.rb | ruby .\interval.rb | ruby ..\histogram.rb -w=5
@echo off
goto end

:long
@echo on
ruby .\toss.rb -p=0.1 100000 | ruby .\interval.rb | ruby ..\histogram.rb -w=5 -u=100
@echo off
goto end

:end
