@echo off
rem This file is automatically generated.

if "%1" == "run" goto run
if "%1" == "long" goto long
goto run

:run
@echo on
@echo '=========== p = 0.99'
ruby .\portfolio.rb -p=0.99 100 | ruby ..\histogram.rb -w=5
@echo '=========== p = 0.7'
ruby .\portfolio.rb -p=0.7 100 | ruby ..\histogram.rb -w=1
@echo off
goto end

:long
@echo on
@echo '=========== p = 0.99'
ruby .\portfolio.rb -p=0.99 -t=500 500 | ruby ..\histogram.rb -w=10 -u=5
@echo '=========== p = 0.7'
ruby .\portfolio.rb -p=0.7 -t=500 500 | ruby ..\histogram.rb -w=2 -u=5
@echo off
goto end

:end
