run:
	./nearest.rb 50 | ../histogram.rb -w=0.1

run1:
	./nearest.rb -d=1 50 | ../histogram.rb -w=0.002

run2:
	./nearest.rb -d=2 50 | ../histogram.rb -w=0.02

run3:
	./nearest.rb -d=3 50 | ../histogram.rb -w=0.02

long:
	./nearest.rb 1000 | ../histogram.rb -w=0.1 -u=10
