@echo off
rem This file is automatically generated.

if "%1" == "run" goto run
if "%1" == "count" goto count
if "%1" == "clong" goto clong
if "%1" == "long" goto long
goto run

:run
@echo on
@echo '=========== pattern 01'
ruby .\pattern.rb -p=01 20
@echo '=========== pattern 11'
ruby .\pattern.rb -p=11 20
@echo off
goto end

:count
@echo on
@echo '=========== pattern 01'
ruby .\pattern.rb -v -p=01 -c=20 5
@echo '=========== pattern 11'
ruby .\pattern.rb -v -p=11 -c=20 5
@echo off
goto end

:clong
@echo on
@echo '=========== pattern 01'
ruby .\pattern.rb -p=01 -c=100 1000 | ruby ..\histogram.rb -w=2 -u=10
@echo '=========== pattern 11'
ruby .\pattern.rb -p=11 -c=100 1000 | ruby ..\histogram.rb -w=2 -u=10
@echo off
goto end

:long
@echo on
@echo '=========== pattern 01'
ruby .\pattern.rb -p=01 1000 | ruby .\length.rb | ruby ..\histogram.rb -w=2 -u=10
@echo '=========== pattern 11'
ruby .\pattern.rb -p=11 1000 | ruby .\length.rb | ruby ..\histogram.rb -w=2 -u=10
@echo off
goto end

:end
